export const mockListings = [
  {
    id: 1,
    price: 725000,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
    userId: 1,
    propertyId: 1,
    tier: 'FEATURED' as const,
    status: 'ACTIVE' as const,
    saleListing: {
      price: 725000,
      priceType: 'FIXED_PRICE' as const,
    },
    property: {
      id: 1,
      media: [
        { image: 'a08cd2c3-6cd8-4a42-aa4e-68e0d4160800', alt: 'Modern house exterior' },
        { image: 'f08471ae-a51d-4a43-9632-7a193b129500', alt: 'Living room' },
      ],
      type: { name: 'Detached' },
      classification: { name: 'House' },
      numberBedrooms: 4,
      numberBathrooms: 3,
      numberReceptions: 2,
      address: {
        street: '42 Victoria Gardens',
        city: 'London',
        postcode: 'SW1A 2AA',
        fullAddress: '42 Victoria Gardens, London, SW1A 2AA',
      },
      bedrooms: [4],
      bathrooms: [3],
      receptions: [2],
    },
    user: {
      id: 1,
      username: 'demo-agent',
      firstName: 'Demo',
      lastName: 'Agent',
      avatar: null,
    },
  },
  {
    id: 2,
    price: 550000,
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
    userId: 1,
    propertyId: 2,
    tier: 'BASIC' as const,
    status: 'ACTIVE' as const,
    saleListing: {
      price: 550000,
      priceType: 'FIXED_PRICE' as const,
    },
    property: {
      id: 2,
      media: [
        { image: 'd451972a-61ee-4153-87b5-7697a4c0dc00', alt: 'Terraced house' },
        { image: 'd181f96f-be34-4e99-2095-eb7319827900', alt: 'Kitchen' },
      ],
      type: { name: 'Terraced' },
      classification: { name: 'House' },
      numberBedrooms: 3,
      numberBathrooms: 2,
      numberReceptions: 1,
      address: {
        street: '18 Elm Street',
        city: 'London',
        postcode: 'N1 2AB',
        fullAddress: '18 Elm Street, London, N1 2AB',
      },
      bedrooms: [3],
      bathrooms: [2],
      receptions: [1],
    },
    user: {
      id: 1,
      username: 'demo-agent',
      firstName: 'Demo',
      lastName: 'Agent',
      avatar: null,
    },
  },
  {
    id: 3,
    price: 425000,
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
    userId: 1,
    propertyId: 3,
    tier: 'BASIC' as const,
    status: 'ACTIVE' as const,
    saleListing: {
      price: 425000,
      priceType: 'OFFERS_OVER' as const,
    },
    property: {
      id: 3,
      media: [
        { image: '6c48e550-09ea-4b56-fb5f-6d9268cd3500', alt: 'Modern apartment' },
        { image: '97774d3c-da7b-4088-fc2e-c773d4436800', alt: 'Bedroom' },
      ],
      type: { name: 'Flat' },
      classification: { name: 'Flat' },
      numberBedrooms: 2,
      numberBathrooms: 1,
      numberReceptions: 1,
      address: {
        street: 'Flat 7, The Heights',
        city: 'London',
        postcode: 'E14 9SH',
        fullAddress: 'Flat 7, The Heights, London, E14 9SH',
      },
      bedrooms: [2],
      bathrooms: [1],
      receptions: [1],
    },
    user: {
      id: 1,
      username: 'demo-agent',
      firstName: 'Demo',
      lastName: 'Agent',
      avatar: null,
    },
  },
]
