import { describe, it, expect } from 'vitest';
import { generateSlots, formatOpenHouseDate, slotLabelFromTime } from '../../../shared/utils/open-house-slots';

// ─── generateSlots ────────────────────────────────────────────────────────────

describe('generateSlots', () => {
  it('generates the correct number of 15-min slots for a 3-hour window', () => {
    const slots = generateSlots('10:00', '13:00', 15);
    expect(slots).toHaveLength(12);
  });

  it('generates the correct number of 30-min slots for a 2-hour window', () => {
    const slots = generateSlots('10:00', '12:00', 30);
    expect(slots).toHaveLength(4);
  });

  it('returns an empty array when start equals end', () => {
    const slots = generateSlots('10:00', '10:00', 15);
    expect(slots).toHaveLength(0);
  });

  it('excludes the final partial slot when window does not divide evenly', () => {
    // 50-min window with 15-min slots → floor(50/15) = 3 full slots
    const slots = generateSlots('10:00', '10:50', 15);
    expect(slots).toHaveLength(3);
  });

  it('formats each slot as "HH:mm–HH:mm"', () => {
    const slots = generateSlots('10:00', '11:00', 15);
    for (const slot of slots) {
      expect(slot).toMatch(/^\d{2}:\d{2}–\d{2}:\d{2}$/);
    }
  });

  it('produces contiguous slots where each slot end equals the next slot start', () => {
    const slots = generateSlots('10:00', '12:00', 15);
    for (let i = 0; i < slots.length - 1; i++) {
      const currentEnd = slots[i]!.split('–')[1];
      const nextStart = slots[i + 1]!.split('–')[0];
      expect(currentEnd).toBe(nextStart);
    }
  });

  it('first slot starts at the given startTime', () => {
    const slots = generateSlots('09:30', '10:30', 15);
    expect(slots[0]).toMatch(/^09:30–/);
  });

  it('last slot ends at the given endTime for evenly divisible windows', () => {
    const slots = generateSlots('10:00', '11:00', 15);
    expect(slots[slots.length - 1]).toMatch(/–11:00$/);
  });

  it('handles hour rollover correctly', () => {
    const slots = generateSlots('10:45', '11:15', 15);
    expect(slots).toHaveLength(2);
    expect(slots[0]).toBe('10:45–11:00');
    expect(slots[1]).toBe('11:00–11:15');
  });

  it('generates a single slot when window exactly equals slotMins', () => {
    const slots = generateSlots('10:00', '10:15', 15);
    expect(slots).toHaveLength(1);
    expect(slots[0]).toBe('10:00–10:15');
  });

  it('pads hours and minutes with leading zeros', () => {
    const slots = generateSlots('09:00', '09:30', 15);
    expect(slots[0]).toBe('09:00–09:15');
    expect(slots[1]).toBe('09:15–09:30');
  });
});

// ─── formatOpenHouseDate ──────────────────────────────────────────────────────

describe('formatOpenHouseDate', () => {
  it('returns a non-empty string', () => {
    const result = formatOpenHouseDate('2026-06-15T12:00:00.000Z');
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  });

  it('includes the abbreviated month name', () => {
    // 2026-06-15 → "Jun"
    const result = formatOpenHouseDate('2026-06-15T12:00:00.000Z');
    expect(result).toMatch(/Jun/);
  });

  it('includes the numeric day', () => {
    const result = formatOpenHouseDate('2026-06-15T12:00:00.000Z');
    expect(result).toMatch(/15/);
  });

  it('includes the abbreviated weekday', () => {
    // 2026-06-15 is a Monday
    const result = formatOpenHouseDate('2026-06-15T12:00:00.000Z');
    expect(result).toMatch(/Mon/);
  });

  it('handles dates stored at UTC noon without weekday drift', () => {
    // Stored at T12:00:00.000Z so UTC±12 zones all land on the same calendar day
    const result = formatOpenHouseDate('2026-01-01T12:00:00.000Z');
    expect(result).toMatch(/Jan/);
    expect(result).toMatch(/1/);
  });
});

// ─── slotLabelFromTime ────────────────────────────────────────────────────────

describe('slotLabelFromTime', () => {
  it('builds a "HH:mm–HH:mm" label for a standard 15-min slot', () => {
    expect(slotLabelFromTime('10:00', 15)).toBe('10:00–10:15');
  });

  it('handles minute overflow into the next hour', () => {
    expect(slotLabelFromTime('10:45', 15)).toBe('10:45–11:00');
  });

  it('handles a 30-min slot duration', () => {
    expect(slotLabelFromTime('14:30', 30)).toBe('14:30–15:00');
  });

  it('handles slot starting at 00:00', () => {
    expect(slotLabelFromTime('00:00', 15)).toBe('00:00–00:15');
  });

  it('pads single-digit minutes with leading zero', () => {
    expect(slotLabelFromTime('09:05', 15)).toBe('09:05–09:20');
  });

  it('matches the format of slots generated by generateSlots', () => {
    const slots = generateSlots('10:00', '11:00', 15);
    const label = slotLabelFromTime('10:00', 15);
    expect(slots[0]).toBe(label);
  });
});
