name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all-tests:
    runs-on: ubuntu-latest
    env:
      # used to generate the Prisma client
      DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
      # used to bootstrap the prisma client
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.4.1

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Generate Prisma client
      run: pnpm prisma generate

    # - name: Run database migrations
    #   run: pnpm prisma migrate deploy

    - name: Run Unit Tests
      run: pnpm test