name: Run Migrations
on:
  push:
    paths:
      - prisma/migrations/**
    branches:
      - main
      - staging

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Apply all pending migrations to the database
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.MAIN_DATABASE_URL }}
          
  staging-migrations:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Apply all pending migrations to the staging database
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}